apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: ocmagent-finalizer-cleanup-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
- apiGroups:
  - "ocmagent.managed.openshift.io"
  resources:
  - ocmagents
  verbs:
  - get
  - list
  - patch
