---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    annotations:
        policy.open-cluster-management.io/categories: CM Configuration Management
        policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        policy.open-cluster-management.io/standards: NIST SP 800-53
    name: backplane-srep-ro
    namespace: openshift-acm-policies
spec:
    disabled: false
    policy-templates:
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: backplane-srep-ro
            spec:
                evaluationInterval:
                    compliant: 2h
                    noncompliant: 45s
                object-templates:
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: v1
                        kind: Namespace
                        metadata:
                            name: openshift-backplane-srep-ro
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: ClusterRole
                        metadata:
                            name: backplane-srep-ro-readers-cluster
                        rules:
                            - apiGroups:
                                - ""
                              resources:
                                - nodes
                                - nodes/proxy
                                - nodes/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - machineconfiguration.openshift.io
                              resources:
                                - machineconfigs
                                - machineconfigpools
                                - kubeletconfigs
                                - containerruntimeconfigs
                                - controllerconfigs
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - machine.openshift.io
                              resources:
                                - machines
                                - machinesets
                                - machinehealthchecks
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - autoscaling.openshift.io
                              resources:
                                - clusterautoscalers
                                - machineautoscalers
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - apiserver.openshift.io
                              resources:
                                - apirequestcounts
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - certificates.k8s.io
                              resources:
                                - certificatesigningrequests
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - avo.openshift.io
                              resources:
                                - vpcendpoints
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - authentication.k8s.io
                              resources:
                                - tokenreviews
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - authorization.k8s.io
                              resources:
                                - localsubjectaccessreviews
                                - selfsubjectaccessreviews
                                - selfsubjectrulesreviews
                                - subjectaccessreviews
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - authorization.openshift.io
                              resources:
                                - localresourceaccessreviews
                                - localsubjectaccessreviews
                                - resourceaccessreviews
                                - selfsubjectrulesreviews
                                - subjectaccessreviews
                                - subjectrulesreviews
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - ""
                              resources:
                                - persistentvolumes
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - ""
                              resources:
                                - namespaces
                                - namespaces/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - config.openshift.io
                                - project.openshift.io
                              resources:
                                - projects
                              verbs:
                                - get
                                - list
                                - watch
                            - nonResourceURLs:
                                - /healthz
                                - /healthz/*
                                - /livez
                                - /livez/*
                                - /metrics
                                - /metrics/*
                                - /readyz
                                - /readyz/*
                                - /version
                                - /version/*
                              verbs:
                                - get
                    - complianceType: mustonlyhave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: rbac.authorization.k8s.io/v1
                        kind: ClusterRole
                        metadata:
                            name: backplane-srep-ro-readers-project
                        rules:
                            - apiGroups:
                                - ""
                              resources:
                                - pods
                                - pods/status
                                - pods/log
                                - services
                                - endpoints
                                - persistentvolumeclaims
                                - events
                                - configmaps
                                - serviceaccounts
                                - replicationcontrollers
                                - replicationcontrollers/scale
                                - resourcequotas
                                - limitranges
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - apps
                              resources:
                                - deployments
                                - deployments/scale
                                - deployments/status
                                - daemonsets
                                - daemonsets/status
                                - replicasets
                                - replicasets/scale
                                - replicasets/status
                                - statefulsets
                                - statefulsets/scale
                                - statefulsets/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - batch
                              resources:
                                - jobs
                                - jobs/status
                                - cronjobs
                                - cronjobs/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - networking.k8s.io
                              resources:
                                - networkpolicies
                                - ingresses
                                - ingresses/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - rbac.authorization.k8s.io
                              resources:
                                - roles
                                - rolebindings
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - autoscaling
                              resources:
                                - horizontalpodautoscalers
                                - horizontalpodautoscalers/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - policy
                              resources:
                                - poddisruptionbudgets
                                - poddisruptionbudgets/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - apps.openshift.io
                              resources:
                                - deploymentconfigs
                                - deploymentconfigs/scale
                                - deploymentconfigs/log
                                - deploymentconfigs/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - build.openshift.io
                              resources:
                                - builds
                                - builds/log
                                - builds/details
                                - buildconfigs
                                - buildconfigs/webhooks
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - route.openshift.io
                              resources:
                                - routes
                                - routes/status
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - image.openshift.io
                              resources:
                                - imagestreams
                                - imagestreams/status
                                - imagestreamtags
                                - imagestreamimages
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - template.openshift.io
                              resources:
                                - templates
                                - templateinstances
                                - processedtemplates
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - monitoring.coreos.com
                              resources:
                                - servicemonitors
                                - podmonitors
                                - prometheusrules
                                - alertmanagers
                                - prometheuses
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - operators.coreos.com
                              resources:
                                - clusterserviceversions
                                - catalogsources
                                - installplans
                                - subscriptions
                                - operatorgroups
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - logging.openshift.io
                              resources:
                                - clusterloggings
                                - clusterlogforwarders
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - velero.io
                              resources:
                                - backups
                                - restores
                                - schedules
                                - backupstoragelocations
                                - volumesnapshotlocations
                                - deletebackuprequests
                                - downloadrequests
                                - podvolumebackups
                                - podvolumerestores
                                - resticrepositories
                                - serverstatusrequests
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - machine.openshift.io
                              resources:
                                - machinehealthchecks
                                - machinesets
                                - machinesets/scale
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - upgrade.managed.openshift.io
                              resources:
                                - upgradeconfigs
                              verbs:
                                - get
                                - list
                                - watch
                            - apiGroups:
                                - security.openshift.io
                              resources:
                                - podsecuritypolicyreviews
                                - podsecuritypolicyselfsubjectreviews
                                - podsecuritypolicysubjectreviews
                              verbs:
                                - get
                                - list
                                - watch
                pruneObjectBehavior: DeleteIfCreated
                remediationAction: enforce
                severity: low
    remediationAction: enforce
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: placement-backplane-srep-ro
    namespace: openshift-acm-policies
spec:
    clusterSelector:
        matchExpressions:
            - key: hypershift.open-cluster-management.io/hosted-cluster
              operator: In
              values:
                - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: binding-backplane-srep-ro
    namespace: openshift-acm-policies
placementRef:
    apiGroup: apps.open-cluster-management.io
    kind: PlacementRule
    name: placement-backplane-srep-ro
subjects:
    - apiGroup: policy.open-cluster-management.io
      kind: Policy
      name: backplane-srep-ro
