---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
    annotations:
        policy.open-cluster-management.io/categories: CM Configuration Management
        policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
        policy.open-cluster-management.io/standards: NIST SP 800-53
    name: osd-cluster-acks-hcp-5.0
    namespace: openshift-acm-policies
spec:
    disabled: false
    policy-templates:
        - objectDefinition:
            apiVersion: policy.open-cluster-management.io/v1
            kind: ConfigurationPolicy
            metadata:
                name: osd-cluster-acks-hcp-5.0
            spec:
                evaluationInterval:
                    compliant: 2h
                    noncompliant: 45s
                object-templates-raw: |
                    - complianceType: musthave
                      metadataComplianceType: musthave
                      objectDefinition:
                        apiVersion: operator.openshift.io/v1
                        kind: CloudCredential
                        metadata:
                          name: cluster
                          annotations:
                            cloudcredential.openshift.io/upgradeable-to: "v5.0"
                remediationAction: enforce
                severity: high
    remediationAction: enforce
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
    name: placement-osd-cluster-acks-hcp-5.0
    namespace: openshift-acm-policies
spec:
    clusterSelector:
        matchExpressions:
            - key: hypershift.open-cluster-management.io/hosted-cluster
              operator: In
              values:
                - "true"
            - key: openshiftVersion-major-minor
              operator: In
              values:
                - "4.22"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
    name: binding-osd-cluster-acks-hcp-5.0
    namespace: openshift-acm-policies
placementRef:
    apiGroup: apps.open-cluster-management.io
    kind: PlacementRule
    name: placement-osd-cluster-acks-hcp-5.0
subjects:
    - apiGroup: policy.open-cluster-management.io
      kind: Policy
      name: osd-cluster-acks-hcp-5.0
