apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedFleetNotification
metadata:
  name: additional-trust-bundle-ca-invalid
  namespace: openshift-ocm-agent-operator
spec:
  fleetNotification:
    name: additional-trust-bundle-ca-invalid
    severity: Major
    summary: "Additional Trust Bundle CA Invalid"
    logType: "Cluster Networking"
    notificationMessage: |-
      Your cluster requires you to take action because one of the Certificate Authority (CA) certificates in the Additional Trusted CA Bundle you have added to your cluster is detected as unparseable or invalid. Please ensure your Additional Trusted CA Bundle represents a bundle of one or more PEM-encoded X.509 certificates that are all concatenated together. For more information, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#trust_bundle_responsibilities_cluster-wide-proxy-configuration
    resendInterval: 24
    references:
      - https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html
---
apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedFleetNotification
metadata:
  name: cluster-proxy-network-degraded
  namespace: openshift-ocm-agent-operator
spec:
  fleetNotification:
    name: cluster-proxy-network-degraded
    severity: Major
    summary: "Cluster-wide Proxy failing readiness checks"
    logType: "Cluster Networking"
    notificationMessage: |-
      Your cluster requires you to take action because your configured cluster-wide proxy is failing to satisfy readiness endpoint reachability checks that can confirm its correct operation. Please verify the availability of your cluster-wide proxy and its ability to proxy egress network traffic from the cluster. For more information on management of the cluster-wide proxy, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html
    resendInterval: 24
    references:
      - https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html
---
apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedFleetNotification
metadata:
  name: additional-trust-bundle-ca-expiring
  namespace: openshift-ocm-agent-operator
spec:
  fleetNotification:
    name: additional-trust-bundle-ca-expiring
    severity: Warning
    summary: "Additional Trust Bundle CA Expiring"
    logType: "Cluster Networking"
    notificationMessage: |-
      Your cluster requires you to take action because one of the Certificate Authority (CA) certificates in the Additional Trusted CA Bundle you have set for your cluster is due to expire. To avoid any potential disruption of service or cluster availability caused by the expiration of the CA certificate, please ensure your Additional Trusted CA Bundle is updated with any new CA certificates required. For more information, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#trust_bundle_responsibilities_cluster-wide-proxy-configuration
    resendInterval: 48
    references:
      - https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html
---
apiVersion: ocmagent.managed.openshift.io/v1alpha1
kind: ManagedFleetNotification
metadata:
  name: additional-trust-bundle-ca-expired
  namespace: openshift-ocm-agent-operator
spec:
  fleetNotification:
    name: additional-trust-bundle-ca-expired
    severity: Critical
    summary: "Additional Trust Bundle CA Expired"
    logType: "Cluster Networking"
    notificationMessage: |-
      Your cluster requires you to take action because one of the Certificate Authority (CA) certificates in the Additional Trusted CA Bundle you have added to your cluster has now reached its expiration date. To avoid any potential disruption of service or cluster availability caused by the expiration of the CA certificate, please ensure your Additional Trusted CA Bundle is updated with any new CA certificates required and remove the expired CA certificates. For more information, please refer to https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html#trust_bundle_responsibilities_cluster-wide-proxy-configuration
    resendInterval: 24
    references:
      - https://docs.openshift.com/rosa/networking/configuring-cluster-wide-proxy.html
