---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oadp-orphaned-schedule-cleanup
  namespace: openshift-adp
subjects:
- kind: ServiceAccount
  name: oadp-orphaned-schedule-cleanup
  namespace: openshift-adp
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: oadp-orphaned-schedule-cleanup
