---
apiVersion: monitoring.rhobs/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: autonode-iam-misconfiguration
    role: alert-rules
  name: autonode-iam-misconfiguration
  namespace: openshift-observability-rhobs
spec:
  groups:
    - name: AutoNodeIAMMisconfigurationFleetNotification
      interval: 60s
      rules:
        - alert: AutoNodeIAMMisconfigurationSRE
          annotations:
            description: "AutoNode encountering IAM-related errors for cluster {{ $labels._id }}, indicating a misconfigured IAM role or instance profile."
            summary: "AutoNode IAM role misconfiguration detected"
          expr: sum by (_id, namespace) (operator_nodeclaim_status_condition_count{reason=~"Unauthorized|InstanceProfileNameInvalid|SpotSLRCreationFailed|AMIAuthorizationFailure"}) > 0 unless on (_id) sre:hcp:alerts_suppressed
          for: 15m
          labels:
            severity: warning
            send_managed_notification: "true"
            managed_notification_template: autonode-iam-misconfiguration
            namespace: "{{ $labels.namespace }}"
