deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  matchExpressions:
    - key: ext-hypershift.openshift.io/cluster-type
      operator: In
      values: ["service-cluster"]
    - key: ext-hypershift.openshift.io/cluster-sector
      operator: In
      values: ["canary"]
