---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/standards: NIST SP 800-53
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
  name: "rosaeng-8224"
  namespace: openshift-acm-policies
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rosaeng-8224
        spec:
          namespaceSelector:
            matchLabels:
              hypershift.openshift.io/hosted-control-plane: "true"
          pruneObjectBehavior: DeleteIfCreated
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: networking.k8s.io/v1
                kind: NetworkPolicy
                metadata:
                  name: rosaeng-8224
                spec:
                  ingress:
                  - from:
                    - namespaceSelector:
                        matchLabels:
                          network.openshift.io/policy-group: ingress
                  podSelector: {}
                  policyTypes:
                  - Ingress
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: "placement-rosaeng-8224"
  namespace: openshift-acm-policies
spec:
  clusterSelector:
    matchExpressions:
      - key: hypershift.open-cluster-management.io/management-cluster
        operator: In
        values:
          - "true"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: "binding-rosaeng-8224"
  namespace: openshift-acm-policies
placementRef:
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
  name: placement-rosaeng-8224
subjects:
  - apiGroup: policy.open-cluster-management.io
    kind: Policy
    name: "rosaeng-8224"
