#!/usr/bin/sh

# make sure 'make' was run before pushing.  requires having no local changes

FILES_CHANGED=$(git status --porcelain | wc -l)

if [ "$FILES_CHANGED" != "0" ];
then
    git stash
    trap "git reset --hard HEAD; git stash pop" EXIT
else
    trap "git reset --hard HEAD" EXIT
fi

./hack/app_sre_pr_check.sh

