---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: rosaeng-62211-delete-image-policy-icsp
rules:
- apiGroups:
  - operator.openshift.io
  resources:
  - imagecontentsourcepolicies
  resourceNames:
  - image-policy
  verbs:
  - get
  - list
  - delete
