apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingAdmissionPolicyBinding
metadata:
  name: autonode-nodepool-guardrails-binding
spec:
  policyName: autonode-nodepool-guardrails
  validationActions: [Deny]
