apiVersion: console.openshift.io/v1
kind: ConsoleNotification
metadata:
  name: upgrade-required
spec:
  backgroundColor: "#EE0000"
  location: "BannerTop"
  text: |-
    An urgent upgrade for your cluster is required to continue receiving support |
  link:
    href: https://cloud.redhat.com/openshift/?plan_id=OSD,ROSA
    text: Access the OpenShift Cluster Manager to schedule an upgrade
