deploymentMode: Policy
clusterSelectors:
  matchExpressions:
    - key: hypershift.open-cluster-management.io/hosted-cluster
      operator: In
      values:
        - "true"
    - key: openshiftVersion-major-minor
      operator: In
      values:
        - "4.22"
policy:
  complianceType: "musthave"