deploymentMode: Policy
clusterSelectors:
  matchExpressions:
    - key: hypershift.open-cluster-management.io/management-cluster
      operator: In
      values:
        - "true"
policy:
  destination: "acm-policies"
  complianceType: "mustonlyhave"
