apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: sre-coo-stack
    role: alert-rules
  name: sre-coo-stack
  namespace: openshift-monitoring
spec:
  groups:
    - name: sre-coo-stack
      rules:
        - alert: COOStackMissingSRE
          expr: |
            absent(kube_deployment_status_replicas{deployment="obo-prometheus-operator", namespace="openshift-operators"}) or
            absent(kube_deployment_status_replicas{deployment="obo-prometheus-operator-admission-webhook", namespace="openshift-operators"}) or
            absent(kube_deployment_status_replicas{deployment="observability-operator", namespace="openshift-operators"})
          for: 15m
          labels:
            severity: critical
            namespace: openshift-operators
          annotations:
            summary: "Cluster Observability Operator or one of its component is absent from the Management Cluster"
            description: |
              The following Cluster Observability Operator (COO) component is absent or has failed to be deployed in the Management Cluster for last 15 mins:
              {{$labels.deployment}} deployment
            runbook_url: https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/COOStackMissingSRE.md

        - alert: COOStackDegradedSRE
          expr: (sum(kube_deployment_spec_replicas{deployment=~"(obo.*)|(observability-operator)", namespace="openshift-operators"}) without (instance, pod)) - (sum(kube_deployment_status_replicas_available{deployment=~"(obo.*)|(observability-operator)", namespace="openshift-operators"}) without (instance, pod)) > 0
          for: 15m
          labels:
            severity: critical
            namespace: openshift-operators
          annotations:
            summary: "Cluster Observability Operator or one of its component is not ready"
            description: "{{$value}} replicas are not ready out of total required replicas for the Cluster Observability Operator (COO) {{$labels.deployment}} deployment"
            runbook_url: https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/COOStackDegradedSRE.md

    - name: sre-coo-workload
      rules:
        - alert: COOWorkloadMissingSRE
          expr: |
            absent(kube_statefulset_status_replicas{statefulset="prometheus-hypershift-monitoring-stack", namespace="openshift-observability-operator"}) or
            absent(kube_statefulset_status_replicas{statefulset="alertmanager-hypershift-monitoring-stack", namespace="openshift-observability-operator"}) or
            absent(kube_statefulset_status_replicas{statefulset="prometheus-rhobs-hypershift-monitoring-stack", namespace="openshift-observability-operator"}) or
            absent(kube_statefulset_status_replicas{statefulset="alertmanager-rhobs-hypershift-monitoring-stack", namespace="openshift-observability-operator"})
          for: 15m
          labels:
            severity: critical
            namespace: openshift-observability-operator
          annotations:
            summary: "Cluster Observability Operator workload is absent from the Management Cluster"
            description: |
              The following Cluster Observability Operator (COO) workload is absent or has failed to be deployed in the Management Cluster for last 15 mins:
              {{$labels.statefulset}} statefulset
            runbook_url: https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/COOWorkloadMissingSRE.md

        - alert: COOWorkloadDegradedSRE
          expr: (kube_statefulset_replicas{namespace="openshift-observability-operator"} - kube_statefulset_status_replicas_ready{namespace="openshift-observability-operator"}) > 0
          for: 60m
          labels:
            severity: critical
            namespace: openshift-observability-operator
            cause: "Pods in the 'openshift-observability-operator' namespace are not all ready"
          annotations:
            summary: "Some pods in the 'openshift-observability-operator' namespace are not ready"
            description: "At least one pod in the 'openshift-observability-operator' namespace has not been ready for the last 60 minutes."
            runbook_url: https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/COOWorkloadDegradedSRE.md

        - alert: COOWorkloadDegradedSRE
          expr: increase(kube_pod_container_status_restarts_total{namespace="openshift-observability-operator"}[10m]) > 0
          for: 30m
          labels:
            severity: critical
            namespace: openshift-observability-operator
            cause: "Pod containers in the 'openshift-observability-operator' namespace are restarting"
          annotations:
            summary: "Some pod in the 'openshift-observability-operator' namespace is stuck in a restart loop"
            description: "Pod {{$labels.pod}} in the 'openshift-observability-operator' namespace has been stuck in restarts for the last 30 minutes."
            runbook_url: https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/COOWorkloadDegradedSRE.md

        - alert: COOWorkloadDegradedSRE
          expr: |
            rate(prometheus_remote_storage_samples_failed_total{namespace="openshift-observability-operator"}[5m]) / rate(prometheus_remote_storage_samples_total{namespace="openshift-observability-operator"}[5m]) > 0.001
          for: 15m
          labels:
            severity: critical
            namespace: openshift-observability-operator
            cause: "Prometheus pods in the 'openshift-observability-operator' namespace cannot remote write to telemeter or RHOBS"
          annotations:
            summary: "Some pods in the 'openshift-observability-operator' namespace cannot remote write to telemeter or RHOBS"
            description: |
              {{ $value | humanizePercentage }} of the time series cannot be sent to {{$labels.url}}
            runbook_url: https://github.com/openshift/ops-sop/blob/master/hypershift/alerts/COOWorkloadDegradedSRE.md