---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: allow-unsigned-nightly-images
rules:
- apiGroups:
  - config.openshift.io
  resources:
  - clusterversions
  - clusterimagepolicies
  verbs:
  - get
  - list
  - patch
  - update
