apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: console-webhook-cleanup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: console-webhook-cleanup
subjects:
- kind: ServiceAccount
  name: console-webhook-cleanup
  namespace: openshift-console-operator
