deploymentMode: "SelectorSyncSet"
selectorSyncSet:
  resourceApplyMode: Sync
  matchExpressions:
  - key: api.openshift.com/version
    operator: In
    values:
      - "4.17"
      - "4.18"
      - "4.19"
      - "4.20"
      - "4.21"
      - "4.22"
