apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-admins-project
rules:
# SRE can portforward pods
- apiGroups:
  - ""
  resources:
  - pods/portforward
  verbs:
  - create
# SRE can review pod security policies
- apiGroups:
  - security.openshift.io
  resources:
  - podsecuritypolicyreviews
  - podsecuritypolicyselfsubjectreviews
  - podsecuritypolicysubjectreviews
  verbs:
  - create
# SRE can view Logging (ClusterLogging and ElasticSearch CRs)
- apiGroups:
  - logging.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view backups
- apiGroups:
  - velero.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view monitoring.coreos.com CustomResources
- apiGroups:
  - monitoring.coreos.com
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
