apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: backplane-srep-admins-cluster
rules:
# SRE can get node-logs
- apiGroups:
  - ""
  resources:
  - nodes/proxy
  verbs:
  - get
# SRE can view projects
- apiGroups:
  - config.openshift.io
  resources:
  - projects
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - project.openshift.io
  resources:
  - projects
  - projectrequests
  verbs:
  - get
  - list
  - watch
# SRE can view namespaces
- apiGroups:
  - ""
  resources:
  - namespaces
  - namespaces/finalize
  verbs:
  - get
  - list
  - watch
# SRE can get all endpoints
- nonResourceURLs:
  - '*'
  verbs:
  - get
#### Start - more perms for srep
# https://issues.redhat.com/browse/OSD-5537
# SRE can create authz/n reviews
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - localsubjectaccessreviews
  - selfsubjectaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - authorization.openshift.io
  resources:
  - localresourceaccessreviews
  - localsubjectaccessreviews
  - resourceaccessreviews
  - selfsubjectrulesreviews
  - subjectaccessreviews
  - subjectrulesreviews
  verbs:
  - create
# SREP can view machineconfigs, machineconfigpools, kubeletconfigs, controllerconfigs
- apiGroups:
  - machineconfiguration.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view machines, machinehealthchecks, machinesets
- apiGroups:
  - machine.openshift.io
  resources:
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view clusterautoscalers and machineautoscalers
- apiGroups:
  - autoscaling.openshift.io
  resources: 
  - '*'
  verbs:
  - get
  - list
  - watch
# SRE can view api request counts
- apiGroups:
  - apiserver.openshift.io
  resources:
  - apirequestcounts
  verbs:
  - get
  - list
  - watch
# SRE can view CSR objects
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - get
  - list
  - watch
# SRE can view vpcendpoints
- apiGroups:
  - avo.openshift.io
  resources:
  - vpcendpoints
  verbs:
  - get
  - list
  - watch
